version: '3.4'

services:
  db:
    container_name: MSSQL
    hostname: mssql
    ports:
     - 1433:1433
    image: "mcr.microsoft.com/mssql/server:2022-latest"
  webstoremvc:
    image: ${DOCKER_REGISTRY-}webstoremvc
    build:
      context: .
      dockerfile: WebStoreMVC/Dockerfile
