name: tests

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
    tags-ignore: "v*"
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest   
    steps:    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore WebStoreMVC.sln
    - name: Build
      run: dotnet build WebStoreMVC.sln --no-restore
    - name: Test
      run: dotnet test WebStoreMVC.sln --no-build --verbosity normal
